// export {default as Header} from './Header';
export {default as SearchBar} from './SearchBar';
export {default as CategoryFilter} from './CategoryFilter';
export {default as PromotionBanner} from './PromotionBanner';
export {default as PopularBrands} from './PopularBrands';
export {default as HotDeals} from './HotDeals';
export {default as BodyTypeSearch} from './BodyTypeSearch';
export {default as NewsBlogs} from './NewsBlogs';
export {default as MostPopularCars} from './MostPopularCars';
export {default as JustArrived} from './JustArrived';
